### ISSUE TITLE
MicroSD not recognized on Gaming Mode after hours of use.

### ISSUE THREAD

**Issue by horford** [Trevo525/btrfdeck#4]
Not sure what the issue is exactly but I can't access my MicroSD on SteamOS. I can see it in the explorer and browse it but cant add it back as a steam library, it gives me the error "Steam library folder is not executable.". In Gaming Mode I think it wants me to format the sd as it can't read it.

**Comment by horford** [comment]
![Screenshot_20220516_200324](https://user-images.githubusercontent.com/7023101/168664214-4ae3bd02-9e26-445b-91ff-12551b45fa1e.png)

**Comment by horford** [comment]
The SD card works fine on Windows and the Steam Library is recognized.
![Khwoe2UBdLcL](https://user-images.githubusercontent.com/7023101/168665579-3aa586c0-f7bb-49d7-b628-ba6bbd40a087.jpg)

**Comment by horford** [comment]
After running your post update script the drive seems to be mounting correctly, well sort of! It still seems to be unrecognizable to Steam. Any idea where I'm going wrong? ![Screenshot_20220516_211614](https://user-images.githubusercontent.com/7023101/168675471-8cc6538b-653a-4b6d-86ed-7c5df90702f2.png)

**Comment by horford** [comment]
[SOLVED] - I had to browse inside the /run/media directory and add the steam library through there.

**Comment by Trevo525** [comment]
When I had a similar issue, I had to go into gaming mode and remove then reinsert my microSD card. I think desktop mode will mount it into a different folder and that's where the problems came in for me. If it was mounted in game mode, then I could switch to desktop mode as much as I wanted.
