### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by Applepiee** [Trevo525/btrfdeck#5]
Is there any way to make the progress bar work?

**Comment by Trevo525** [comment]
What progress bar are you referring to? I reformatted two microSD cards last night in my Steam Deck and the progress bar in the "Game Mode" menu worked for "Testing" and "Formatting". I could be missing something though.

**Comment by Applepiee** [comment]
Sorry for not being specific. I meant that the original one has a percentage 0-100% until completion. One of my SD cards was corrupted just now and I wasn't sure if it was still doing anything, lol. So I formatted it through windows.

**Comment by Trevo525** [comment]
I don't remember it every having a percentage, but I believe you. However, the actual changes I made are very simple and personally, I don't see a way to implement that. If someone can guide me in the right direction, I'd possibly make the changes. But, to be honest, I don't want to over-complicate this project and the progress bar works, just without a percentage.
